src/main/java/com/mycompany/Controller/RemittanceController.java
package com.mycompany.Controller;

import com.mycompany.Entity.Remittance;
import com.mycompany.Controller.util.JsfUtil;
import com.mycompany.Controller.util.PaginationHelper;
import com.mycompany.Facade.RemittanceFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("remittanceController")
@SessionScoped
public class RemittanceController implements Serializable {

    private Remittance current;
    private DataModel items = null;
    @EJB
    private com.mycompany.Facade.RemittanceFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public RemittanceController() {
    }

    public Remittance getSelected() {
        if (current == null) {
            current = new Remittance();
            selectedItemIndex = -1;
        }
        return current;
    }

    private RemittanceFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Remittance) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Remittance();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Admin").getString("RemittanceCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Admin").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Remittance) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Admin").getString("RemittanceUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Admin").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Remittance) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Admin").getString("RemittanceDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Admin").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Remittance getRemittance(java.lang.Long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Remittance.class)
    public static class RemittanceControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RemittanceController controller = (RemittanceController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "remittanceController");
            return controller.getRemittance(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Remittance) {
                Remittance o = (Remittance) object;
                return getStringKey(o.getPkRemittanceId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Remittance.class.getName());
            }
        }

    }

}

src/main/webapp/remittance/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <ui:composition template="/template.xhtml"
                    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    xmlns:h ="http://xmlns.jcp.org/jsf/html"
                    xmlns:f ="http://xmlns.jcp.org/jsf/core"
                    xmlns:p ="http://primefaces.org/ui">
        <ui:define name="title">
            <h:outputText></h:outputText>
        </ui:define>
        <ui:define name="body"><style>
                .orange
                {
                    display: inline-block; margin: 10px;
                    background: #FFCC00; border: 1px solid rgba(0,0,0,0.15); border-radius: 4px; transition: all 0.3s ease-out;
                    box-shadow: inset 0 1px 0 rgba(255,255,255,0.5), 0 2px 2px rgba(0,0,0,0.3), 0 0 4px 1px rgba(0,0,0,0.2); text-decoration: none;
                    text-shadow: 0 1px gray; color: white; padding: 3px;
                }
                .secDiv
                {
                    position: absolute; left:8%; width: 80%; top: 50px; display: inline-block; margin: 10px;
                    padding: 8px 15px; border: 1px solid rgba(0,0,0,0.15); border-radius: 4px; transition: all 0.3s ease-out;
                    box-shadow: inset 0 1px 0 rgba(255,255,255,0.5), 0 2px 2px rgba(0,0,0,0.3), 0 0 4px 1px rgba(0,0,0,0.2), inset 0 3px 2px rgba(255,255,255,.22), 
                        inset 0 -3px 2px rgba(0,0,0,.15), inset 0 20px 10px rgba(255,255,255,.12), 0 0 4px 1px rgba(0,0,0,.1), 0 3px 2px rgba(0,0,0,.2);
                }
                .mainDiv
                {
                    position: absolute; left:0%; width: 96%; top: 40px; height:700px; display: inline-block; margin: 10px;
                    padding: 8px 15px; border: 1px solid rgba(0,0,0,0.15); border-radius: 4px; transition: all 0.3s ease-out;
                    box-shadow: inset 0 1px 0 rgba(255,255,255,0.5), 0 2px 2px rgba(0,0,0,0.3), 0 0 4px 1px rgba(0,0,0,0.2); text-decoration: none;
                    text-shadow: 0 1px rgba(255,255,255,0.7); opacity:0.3;
                }.Save
                {
                    height: 20px;
                    width: 20px;
                    background:grey url('../img/Save.png') no-repeat;
                }
            </style>
            <div style="position: relative;">
                <img src="../img/Banner.png"/>
            </div>

            <div style="position: relative;">
                <body style="background-color: white;"> 
                    <br/><br/>
                    <div class="secDiv" style="position: absolute; top:50px; left: 10%;">
                        <div class="title ui-widget-header ui-corner-all" style="height: 40px;">
                            <div style="position: absolute; top: 13px;">
                                &nbsp;&nbsp;<label style=" font-size: x-large; ">Create New Remittance</label>
                            </div>
                        </div>
                        <br/>
                        <h:panelGroup id="messagePanel" layout="block">
                            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                        </h:panelGroup>
                        <center>
                            <h:form>
                                <h:link styleClass="orange" outcome="/index" value="Home"/>
                                <h:commandLink styleClass="orange" action="#{remittanceController.prepareList}" value="Remittance List" immediate="true"/>
                                <br/>
                                <br/>
                                <p:panelGrid columns="2">
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_pkRemittanceId}" for="pkRemittanceId" />
                                    <p:inputText id="pkRemittanceId" value="#{remittanceController.selected.pkRemittanceId}" title="#{admin.CreateRemittanceTitle_pkRemittanceId}" required="false" disabled="true" requiredMessage="#{admin.CreateRemittanceRequiredMessage_pkRemittanceId}"/>
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_currencyFrom}" for="currencyFrom" />
                                    <p:inputText id="currencyFrom" value="#{remittanceController.selected.currencyFrom}" title="#{admin.CreateRemittanceTitle_currencyFrom}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_currencyTo}" for="currencyTo" />
                                    <p:inputText id="currencyTo" value="#{remittanceController.selected.currencyTo}" title="#{admin.CreateRemittanceTitle_currencyTo}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_forexRate}" for="forexRate" />
                                    <p:inputText id="forexRate" value="#{remittanceController.selected.forexRate}" title="#{admin.CreateRemittanceTitle_forexRate}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_amountFrom}" for="amountFrom" />
                                    <p:inputText id="amountFrom" value="#{remittanceController.selected.amountFrom}" title="#{admin.CreateRemittanceTitle_amountFrom}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_remittanceFee}" for="remittanceFee" />
                                    <p:inputText id="remittanceFee" value="#{remittanceController.selected.remittanceFee}" title="#{admin.CreateRemittanceTitle_remittanceFee}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_remittanceMonth}" for="remittanceMonth" />
                                    <p:inputText id="remittanceMonth" value="#{remittanceController.selected.remittanceMonth}" title="#{admin.CreateRemittanceTitle_remittanceMonth}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_latestServerTransactionDate}" for="latestServerTransactionDate" />
                                    <p:inputText id="latestServerTransactionDate" value="#{remittanceController.selected.latestServerTransactionDate}" title="#{admin.CreateRemittanceTitle_latestServerTransactionDate}" >
                                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                    </p:inputText>
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_latestDeviceTransactionDate}" for="latestDeviceTransactionDate" />
                                    <p:inputText id="latestDeviceTransactionDate" value="#{remittanceController.selected.latestDeviceTransactionDate}" title="#{admin.CreateRemittanceTitle_latestDeviceTransactionDate}" >
                                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                    </p:inputText>
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_remittanceControlNumber}" for="remittanceControlNumber" />
                                    <h:inputText id="remittanceControlNumber" value="#{remittanceController.selected.remittanceControlNumber}" title="#{admin.CreateRemittanceTitle_remittanceControlNumber}" />
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_fkDeviceId}" for="fkDeviceId" />
                                    <p:selectOneMenu id="fkDeviceId" value="#{remittanceController.selected.fkDeviceId}">
                                        <f:selectItems value="#{deviceController.itemsAvailableSelectOne}"/>
                                    </p:selectOneMenu>
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_fkCfgRemittanceStatusId}" for="fkCfgRemittanceStatusId" />
                                    <p:selectOneMenu id="fkCfgRemittanceStatusId" value="#{remittanceController.selected.fkCfgRemittanceStatusId}">
                                        <f:selectItems value="#{cfgRemittanceStatusController.itemsAvailableSelectOne}"/>
                                    </p:selectOneMenu>
                                    <h:outputLabel value="#{admin.CreateRemittanceLabel_fkAppuserId}" for="fkAppuserId" />
                                    <p:selectOneMenu id="fkAppuserId" value="#{remittanceController.selected.fkAppuserId}">
                                        <f:selectItems value="#{appuserController.itemsAvailableSelectOne}"/>
                                    </p:selectOneMenu>
                                </p:panelGrid>
                                <br />
                                <h:commandLink styleClass="orange Save" action="#{remittanceController.create}" title="Save" />
                            </h:form>
                        </center>
                        <br/>
                        <br/>
                        <br/>
                    </div>
                </body>
            </div>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/remittance/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <ui:composition template="/template.xhtml"
                    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    xmlns:h ="http://xmlns.jcp.org/jsf/html"
                    xmlns:f ="http://xmlns.jcp.org/jsf/core"
                    xmlns:p ="http://primefaces.org/ui">
        <ui:define name="title">
            <h:outputText></h:outputText>
        </ui:define>
        <ui:define name="body"><style>
                .orange
                {
                    display: inline-block; margin: 10px;
                    background: #FFCC00; border: 1px solid rgba(0,0,0,0.15); border-radius: 4px; transition: all 0.3s ease-out;
                    box-shadow: inset 0 1px 0 rgba(255,255,255,0.5), 0 2px 2px rgba(0,0,0,0.3), 0 0 4px 1px rgba(0,0,0,0.2); text-decoration: none;
                    text-shadow: 0 1px gray; color: white; padding: 3px;
                }
                .secDiv
                {
                    position: absolute; left:8%; width: 80%; top: 50px; display: inline-block; margin: 10px;
                    padding: 8px 15px; border: 1px solid rgba(0,0,0,0.15); border-radius: 4px; transition: all 0.3s ease-out;
                    box-shadow: inset 0 1px 0 rgba(255,255,255,0.5), 0 2px 2px rgba(0,0,0,0.3), 0 0 4px 1px rgba(0,0,0,0.2), inset 0 3px 2px rgba(255,255,255,.22), 
                        inset 0 -3px 2px rgba(0,0,0,.15), inset 0 20px 10px rgba(255,255,255,.12), 0 0 4px 1px rgba(0,0,0,.1), 0 3px 2px rgba(0,0,0,.2);
                }
                .mainDiv
                {
                    position: absolute; left:0%; width: 96%; top: 40px; height:700px; display: inline-block; margin: 10px;
                    padding: 8px 15px; border: 1px solid rgba(0,0,0,0.15); border-radius: 4px; transition: all 0.3s ease-out;
                    box-shadow: inset 0 1px 0 rgba(255,255,255,0.5), 0 2px 2px rgba(0,0,0,0.3), 0 0 4px 1px rgba(0,0,0,0.2); text-decoration: none;
                    text-shadow: 0 1px rgba(255,255,255,0.7); opacity:0.3;
                }
                .Save
                {
                    height: 20px;
                    width: 20px;
                    background:grey url('../img/Save.png') no-repeat;
                }
                .View
                {
                    height: 20px;
                    width: 20px;
                    background:grey url('../img/View.png') no-repeat;
                }
            </style>
            <div style="position: relative;">
                <img src="../img/Banner.png"/>
            </div>

            <div style="position: relative;">
                <body style="background-color: white;"> 
                    <br/><br/>
                    <div class="secDiv" style="position: absolute; top:50px; left: 10%;">
                        <div class="title ui-widget-header ui-corner-all" style="height: 40px;">
                            <div style="position: absolute; top: 13px;">
                                &nbsp;&nbsp;<label style=" font-size: x-large; ">Edit Existing Remittance Details</label>
                            </div>
                        </div>
                        <br/>
                        <h:panelGroup id="messagePanel" layout="block">
                            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                        </h:panelGroup>
                        <center>
                            <h:form>
                                <h:link styleClass="orange" outcome="/index" value="Home" />
                                <h:commandLink styleClass="orange" action="#{remittanceController.prepareList}" value="Remittance List" immediate="true"/>
                                <br/>
                                <br/>
                                <p:panelGrid columns="2">
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_pkRemittanceId}" for="pkRemittanceId" />
                                    <p:inputText id="pkRemittanceId" value="#{remittanceController.selected.pkRemittanceId}" title="#{admin.EditRemittanceTitle_pkRemittanceId}" required="true" requiredMessage="#{admin.EditRemittanceRequiredMessage_pkRemittanceId}"/>
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_currencyFrom}" for="currencyFrom" />
                                    <p:inputText id="currencyFrom" value="#{remittanceController.selected.currencyFrom}" title="#{admin.EditRemittanceTitle_currencyFrom}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_currencyTo}" for="currencyTo" />
                                    <p:inputText id="currencyTo" value="#{remittanceController.selected.currencyTo}" title="#{admin.EditRemittanceTitle_currencyTo}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_forexRate}" for="forexRate" />
                                    <p:inputText id="forexRate" value="#{remittanceController.selected.forexRate}" title="#{admin.EditRemittanceTitle_forexRate}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_amountFrom}" for="amountFrom" />
                                    <p:inputText id="amountFrom" value="#{remittanceController.selected.amountFrom}" title="#{admin.EditRemittanceTitle_amountFrom}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_remittanceFee}" for="remittanceFee" />
                                    <p:inputText id="remittanceFee" value="#{remittanceController.selected.remittanceFee}" title="#{admin.EditRemittanceTitle_remittanceFee}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_remittanceMonth}" for="remittanceMonth" />
                                    <p:inputText id="remittanceMonth" value="#{remittanceController.selected.remittanceMonth}" title="#{admin.EditRemittanceTitle_remittanceMonth}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_latestServerTransactionDate}" for="latestServerTransactionDate" />
                                    <p:inputText id="latestServerTransactionDate" value="#{remittanceController.selected.latestServerTransactionDate}" title="#{admin.EditRemittanceTitle_latestServerTransactionDate}" >
                                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                    </p:inputText>
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_latestDeviceTransactionDate}" for="latestDeviceTransactionDate" />
                                    <p:inputText id="latestDeviceTransactionDate" value="#{remittanceController.selected.latestDeviceTransactionDate}" title="#{admin.EditRemittanceTitle_latestDeviceTransactionDate}" >
                                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                    </p:inputText>
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_remittanceControlNumber}" for="remittanceControlNumber" />
                                    <p:inputText id="remittanceControlNumber" value="#{remittanceController.selected.remittanceControlNumber}" title="#{admin.EditRemittanceTitle_remittanceControlNumber}" />
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_fkDeviceId}" for="fkDeviceId" />
                                    <p:selectOneMenu id="fkDeviceId" value="#{remittanceController.selected.fkDeviceId}">
                                        <f:selectItems value="#{deviceController.itemsAvailableSelectOne}"/>
                                    </p:selectOneMenu>
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_fkCfgRemittanceStatusId}" for="fkCfgRemittanceStatusId" />
                                    <p:selectOneMenu id="fkCfgRemittanceStatusId" value="#{remittanceController.selected.fkCfgRemittanceStatusId}">
                                        <f:selectItems value="#{cfgRemittanceStatusController.itemsAvailableSelectOne}"/>
                                    </p:selectOneMenu>
                                    <h:outputLabel value="#{admin.EditRemittanceLabel_fkAppuserId}" for="fkAppuserId" />
                                    <p:selectOneMenu id="fkAppuserId" value="#{remittanceController.selected.fkAppuserId}">
                                        <f:selectItems value="#{appuserController.itemsAvailableSelectOne}"/>
                                    </p:selectOneMenu>
                                </p:panelGrid>
                                <br/>
                                <h:commandLink styleClass="orange Save" action="#{remittanceController.update}" title="Save"/>
                                <h:link styleClass="orange View" outcome="View"  title="View"/>
                            </h:form>
                        </center>
                        <br/>
                        <br/>
                        <br/>
                    </div>
                </body>
            </div>
        </ui:define>
    </ui:composition>

</html>